### ISSUE TITLE
edge weights question

### ISSUE THREAD

**Issue by caijiangyao1991** [yamaguchiyuto/label_propagation#1]
hi  @yamaguchiyuto ,  i have a question about your algorithm ,why  CAMLP don't consider the weights of the edges?  i think it's common to think the label of the unlabeled node should  based more on the neighbors with higher weights, are there any reasons that making you do not consinder weights?

**Comment by yamaguchiyuto** [comment]
Why do you think the weights of edges are not considered? I think the weights in the passed `graph` are taken into account in `_build_propagation_matrix`.

https://github.com/yamaguchiyuto/label_propagation/blob/4441dd43b61619ad9528bd30552f611867b12bac/label_propagation.py#L321


You can pass the weighted graph as described in README.

**Comment by caijiangyao1991** [comment]
@yamaguchiyuto  thanks  for your answer， i have another question , if it is a Homophily network , i think the H should be I  with diagonal elements 1 and off-diagonal elements 0 , means if the node is blue the neighbor node is blue  like your Figure 1 in your paper

**Comment by yamaguchiyuto** [comment]
That is correct.

**Comment by caijiangyao1991** [comment]
@yamaguchiyuto  hi , i make up some data but i got a error
IndexError: index 10 is out of bounds for axis 0 with size 10
 self.F_[x]  get data through x ,but x is the id may bigger than index,
#sample.label
0 0
1 1
2 0
3 1
4 1
5 0
6 0
7 0
10 0
11 1

D:\Anaconda\python.exe F:/project/network/label_propagation/test_caicai.py
x_test:[ 2 10  4 11  1]
self.F_[[1.         0.        ]
 [0.53394218 0.46605782]
 [0.53883216 0.46116784]
 [0.         1.        ]
 [0.56364159 0.43635841]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.50431468 0.49568532]
 [0.5        0.5       ]]
Traceback (most recent call last):
  File "F:/project/network/label_propagation/test_caicai.py", line 25, in <module>
    predicted = OMNI.predict(x_test)
  File "F:\project\network\label_propagation\label_propagation.py", line 87, in predict
    probas = self.predict_proba(x)
  File "F:\project\network\label_propagation\label_propagation.py", line 104, in predict_proba
    z = np.sum(self.F_[x], axis=1)
IndexError: index 10 is out of bounds for axis 0 with size 10

**Comment by yamaguchiyuto** [comment]
What was your edgelist file?

**Comment by caijiangyao1991** [comment]
@yamaguchiyuto 
#edgelist
0 1 3
1 2 2
2 3 3
3 1 1
4 3 1
5 3 2
6 2 1
7 8 1
8 9 2
9 10 2
10 1 3
12 3 2
11 12 1
13 14 2
14 15 2
15 16 1

**Comment by yamaguchiyuto** [comment]
Wait, is that your code? Then I can't answer anything because I don't know your code :/

**Comment by caijiangyao1991** [comment]
@yamaguchiyuto sorry to borther you ,  i thought you want to see my edgelist data, so i post it, this is my code then :
`import numpy as np
import networkx as nx
from scipy import sparse
from label_propagation import OMNI
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from scipy.sparse import csr_matrix

def read_labelfile(f):
    label_data = np.genfromtxt(f, delimiter=' ', dtype=int)
    return label_data[:,0],label_data[:,1]

x,y = read_labelfile('./data/sample.label')
G = nx.read_edgelist('./data/sample1.edgelist', nodetype=int)
A = nx.to_scipy_sparse_matrix(G,nodelist=x)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.5,random_state=0)
OMNI = OMNI(graph=A,lamb=1.0)
OMNI.fit(x_train,y_train)
predicted = OMNI.predict(x_test)`

#sample1.edgelist
0 1
1 2
2 3
3 1
4 3
5 3
6 2
7 8
8 9
9 10
10 1
12 3
11 12
13 14
14 15
15 16
#sample.label
0 0
1 1
2 0
3 1
4 1
5 0
6 0
7 0
10 0
11 1

#error
Traceback (most recent call last):
  File "F:/project/network/label_propagation/test_caicai.py", line 24, in <module>
    predicted = OMNI.predict(x_test)
  File "F:\project\network\label_propagation\label_propagation.py", line 87, in predict
x_test:[ 2 10  4 11  1]
self.F_[[1.         0.        ]
 [0.53394218 0.46605782]
 [0.53883216 0.46116784]
 [0.         1.        ]
 [0.56364159 0.43635841]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.50431468 0.49568532]
 [0.5        0.5       ]]
    probas = self.predict_proba(x)
  File "F:\project\network\label_propagation\label_propagation.py", line 104, in predict_proba
    z = np.sum(self.F_[x], axis=1)
IndexError: index 10 is out of bounds for axis 0 with size 10

**Comment by yamaguchiyuto** [comment]
You need to pass nodelist=[0, 1, ..., 16] to `nx.to_scipy_sparse_matrix()`. You may want to read this: https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.convert_matrix.to_scipy_sparse_matrix.html

**Comment by caijiangyao1991** [comment]
@yamaguchiyuto  thanks !
